
# Whether to output when entities are removed
output_to_console: false

# All autorun enabled groups will be executed with this delay between runs.
# Default is 1200 ticks, or 1 minute
ticks_between_run: 1200

# When true, exiting a vehicle will reset its ticks lived.
# Useful to remove vehicles only when they have been empty for a while
vehicle_reset_ticks_lived: false

worlds: []

# When true, worlds represents all the worlds this cannot run in at a global level
worlds_is_blacklist: true

SpawnerFarms:
  max_entities: 50
  max_density: 0.2
# min_ticks_lived: 0
  autorun: true
# check_only: false
# warn_threshold: 0
# worlds: []
# worlds_is_blacklist: true
  mob_types:
   - ZOMBIE
   - SPIDER
   - CAVE_SPIDER
   - SKELETON
   - BLAZE
   - SILVERFISH 