#Enable Debugging
debug: false
# Whether to output when entities are removed
output_to_console: false

# All autorun enabled groups will be executed with this delay between runs.
# Default is 1200 ticks, or 1 minute
ticks_between_run: 1200

# When true, exiting a vehicle will reset its ticks lived.
# Useful to remove vehicles only when they have been empty for a while
vehicle_reset_ticks_lived: false

worlds: []

# When true, worlds represents all the worlds this cannot run in at a global level
worlds_is_blacklist: true

SpawnerFarms:
  max_entities: 50
  max_density: 0.2
# min_ticks_lived: 0
  autorun: true
# check_only: false
# warn_threshold: 0
# worlds: []
# worlds_is_blacklist: true
  filter:
   ZOMBIE: include
   SPIDER: include
   CAVE_SPIDER: include
   SKELETON: include
   BLAZE: include
   SILVERFISH : include
# This is an example per-chunk limit
# This is just another group and can be named anything
# the important thing for this group is 'chunk_limit'
ChunkLimit:
  max_entities: 40
  # Sets this group to be bound to a chunk. max_density is ignored when this is set
  chunk_limit: true
  # The new way of defining allowed / denied entities, replacing 'mob_types'
  filter:
    all: include
    specials: ignore